### ISSUE TITLE
dataset的文件格式及读取问题

### ISSUE THREAD

**Issue by narutomst** [oubahe/GSA-PSO-SVR#2]
你好，这个dataset是什么格式？该如何读取？

**Comment by oubahe** [comment]
直接download下来就OK，应该是csv格式的或者txt




| |
oubahe
邮箱：oubahe@126.com
|

Signature is customized by Netease Mail Master

在2019年05月15日 21:18，narutomst 写道：

你好，这个dataset是什么格式？该如何读取？

**Comment by narutomst** [comment]
这个数据集dataset没有格式，能用notepad++打开，能正常查看数据，但是dataset没有文件扩展名，不知道怎么读取。每次到读取文件这里就报错了

---> 15 data = pd.read_excel('modeling_data.xlsx',sheetname='Area1_Load')
     16 features=pd.read_excel('modeling_data.xlsx',sheetname='Area1_Weather')
     17 ## features前向填充缺失值
FileNotFoundError: [Errno 2] No such file or directory: 'modeling_data.xlsx'

**Comment by oubahe** [comment]
我上传的时候是直接上传的数据，读者需要自己读取进行格式转换，另外code的数据处理部分可能还需要读者自己做相应的调整。




| |
oubahe
邮箱：oubahe@126.com
|

Signature is customized by Netease Mail Master

在2019年05月15日 22:07，narutomst 写道：

这个数据集dataset没有格式，能用notepad++打开，能正常查看数据，但是dataset没有文件扩展名，不知道怎么读取。每次到读取文件这里就报错了

---> 15 data = pd.read_excel('modeling_data.xlsx',sheetname='Area1_Load')
16 features=pd.read_excel('modeling_data.xlsx',sheetname='Area1_Weather')
17 ## features前向填充缺失值
FileNotFoundError: [Errno 2] No such file or directory: 'modeling_data.xlsx'

**Comment by narutomst** [comment]
你好，请问在不修改（或者尽量少修改）程序代码的情况下，该如何转换数据的格式？我是初学者，有些地方不懂。

**Comment by oubahe** [comment]
数据处理保存部分以及路径等还是要做适当处理的,毕竟机器和环境都不一样，首先把数据保存好生成一个csv文件然后理解代码的意思将数据预处理部分修改后应该就没问题了




| |
oubahe
邮箱：oubahe@126.com
|

Signature is customized by Netease Mail Master

在2019年05月16日 11:31，narutomst 写道：

你好，请问在不修改（或者尽量少修改）程序代码的情况下，该如何转换数据的格式？我是初学者，有些地方不懂。

**Comment by narutomst** [comment]
`################################### 数据读取与预处理 ###############################################
data = pd.read_excel('modeling_data.xlsx',sheetname='Area1_Load')
features=pd.read_excel('modeling_data.xlsx',sheetname='Area1_Weather')`
你好，我把dataset的数据已经复制到modeling_data.xlsx里面了，根据这两条语句中的第二个参数，我应该把数据分开放在两个sheet中吗？每个sheet中应该放哪几列数据？还有就是每一列数据的名称是什么？肯定不是汉字吧？

**Comment by narutomst** [comment]
`################ `数据读取与预处理###############################################`
`data = pd.read_excel('modeling_data.xlsx',sheetname='Area1_Load')`
`features=pd.read_excel('modeling_data.xlsx',sheetname='Area1_Weather')`
你好，我把dataset中的6列数据已经复制到modeling_data.xlsx中了。从上面两条语句看，数据应该是要放在两个sheet中吧？那么每个sheet中分别放哪几列数据？另外，每一列数据的名称是什么？肯定不是现在的汉字吧？

**Comment by narutomst** [comment]
################################### 数据读取与预处理 ###############################################
data = pd.read_excel('modeling_data.xlsx',sheetname='Area1_Load')
features=pd.read_excel('modeling_data.xlsx',sheetname='Area1_Weather')
你好，我把dataset中的6列数据已经复制到modeling_data.xlsx中了。从上面两条语句看，数据应该是要放在两个sheet中吧？那么每个sheet中分别放哪几列数据？另外，每一列数据的名称是什么？肯定不是现在的汉字吧？

**Comment by narutomst** [comment]
时间	最高温度℃	最低温度℃	平均温度℃	相对湿度(平均)	降雨量（mm）
20120101	19.5	12.1	15.8	63	0
20120102	20	13	16	59	0
20120103	18.7	14.2	15.8	72	0
20120104	14.9	9.3	10.9	62	0

你上传的dataset内容是这样子的，你确定没有弄错吗？这个怎么来预测电力负荷？

**Comment by oubahe** [comment]
这是我自己根据我自己的需求划分的，一般来说读取csv的时候不需要sheet名只读一个表，每一列就是一个特征，数据文件第一行有说明特征名字，读取csv的时候可以标注每一列的名字用英文名，例如温度可以用temp




| |
oubahe
邮箱：oubahe@126.com
|

Signature is customized by Netease Mail Master

在2019年05月16日 15:12，narutomst 写道：

################################### 数据读取与预处理 ###############################################
data = pd.read_excel('modeling_data.xlsx',sheetname='Area1_Load')
features=pd.read_excel('modeling_data.xlsx',sheetname='Area1_Weather')
你好，我把dataset中的6列数据已经复制到modeling_data.xlsx中了。从上面两条语句看，数据应该是要放在两个sheet中吧？那么每个sheet中分别放哪几列数据？另外，每一列数据的名称是什么？肯定不是现在的汉字吧？

**Comment by narutomst** [comment]
先得把程序跑通了，才可能有后面自己的修改，你的数据集和程序是匹配的吗？你可以把你能跑通的程序和数据集一起上传。这样别人才有可能跑通，才有后面的相互交流学习。否则，你上传的数据集和程序不匹配，后面的人是没办法学习的，更何谈相互交流呢？

**Comment by oubahe** [comment]
每一份数据集都是一样的但每个人都的处理都不一样。不可能每处理一次保存一个csv就上传一次，而且这个涉及专利无法完全公开我自己处理后的成功成果




| |
oubahe
邮箱：oubahe@126.com
|

Signature is customized by Netease Mail Master

在2019年05月16日 15:39，narutomst 写道：

先得把程序跑通了，才可能有后面自己的修改，你的数据集和程序是匹配的吗？你可以把你能跑通的程序和数据集一起上传。这样别人才有可能跑通，才有后面的相互交流学习。否则，你上传的数据集和程序不匹配，后面的人是没办法学习的，更何谈相互交流呢？

**Comment by narutomst** [comment]
我不是说要你处理后的数据集，你说过数据集是公开的，那你就给出个链接吧
